### ISSUE TITLE
Comparison with DataLoader

### ISSUE THREAD

**Issue by NeoPhi** [codenothing/burst-valve#1]
It would be interesting to see a comparison and benchmark of this library against https://github.com/graphql/dataloader/ which supports similar patterns.

**Comment by codenothing** [comment]
A benchmark or comparison wouldn't be fair as DataLoader and BurstValve have two different priorities. DataLoader is built around caching and per request data fetching, whereas BurstValve is built around app wide data fetching with zero caching.

**Comment by codenothing** [comment]
I was curious about what a benchmark would look like even with a discrepancy in approach. I've disabled cache on the data loader side to try to get as close as a match as possible, with DataLoader doing pure batching and BurstValve doing queuing. Here's the server code:

```ts
interface Customer {
  id: string;
  name: string;
}

const mysqlBurst = new BurstValve(async (id) => {
  return new Promise<Customer>((resolve, reject) => {
    pool.query(
      `SELECT id, name FROM customers WHERE id = ?`,
      [id],
      (e, results) => {
        if (e || !results || !results[0]) {
          reject(e || new Error(`Customer not found`));
        } else {
          resolve(results[0]);
        }
      }
    );
  });
});

const loader = new DataLoader<string, Customer>(
  async (ids) => {
    return await Promise.all(
      ids.map((id) => {
        return new Promise<Customer>((resolve, reject) => {
          pool.query(
            `SELECT id, name FROM customers WHERE id = ?`,
            [id],
            (e, results) => {
              if (e || !results || !results[0]) {
                reject(e || new Error(`Customer not found`));
              } else {
                resolve(results[0]);
              }
            }
          );
        });
      })
    );
  },
  // Disable cache to match BurstValve
  { cache: false }
);

app.get("/mysql-burst-valve/:id", async (req, res) => {
  try {
    const customer = await mysqlBurst.fetch(req.params.id);
    res.status(200).send(`ID: ${customer.id}, NAME: ${customer.name}`);
  } catch {
    res.status(500).send(`Unknown Error`);
  }
});

app.get("/mysql-data-loader/:id", async (req, res) => {
  try {
    const customer = await loader.load(req.params.id);
    res.status(200).send(`ID: ${customer.id}, NAME: ${customer.name}`);
  } catch {
    res.status(500).send(`Unknown Error`);
  }
});
```

And the results were what I expected, running 100 concurrent requests for 15s without caching enabled shows a 2x improvement on BurstValve:

|                 | Run 1        | Run 2        | Run 3        |
| --------------- | ------------ | ------------ | ------------ |
| With BurstValve | 20,422 req/s | 19,967 req/s | 20,035 req/s |
| With DataLoader | 10,211 req/s | 10,144 req/s | 10,272 req/s |

This can be attributed to the fact that DataLoader batching only occurs during the same event loop, where as BurstValve "batching" occurs during the entire time the fetch process takes.
